name: Docker Image Publish

#env:
  
on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: $ {{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build Env
      uses: docker/setup-buildx-action@v1
      
    - name: Build and Deploy
      uses: docker/build-push-action@v2
      with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ymldocker
