name: Docker Image CIO

on:
  push:
    branches: [ main ]
    paths: 
      - 'P_One_ConsoleApp/**/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASS}}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASS
    - name: Build the Docker image
      run: docker build build ./OlympicGamesApp/OlympicGames.App --tag dangapp:$(date +%Y%m%d%H)
      
    - name: Tag the image
      run: docker tag dangapp:$(date +%Y%m%d%H) ${{secrets.DOCKER_HUB_USERNAME}}/projectoneapp:dangapp
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/projectoneapp:dangapp








#name: Docker Image Publish

#env:
  
#on:
#  push:
#    branches: [main]
  
#jobs:
 # build:
 #   runs-on: ubuntu-latest
 #   steps:
 #   - name: Checkout
 #     uses: actions/checkout@v2
 #     
 #   - name: Docker Setup1
 #     uses: docker/login-action@v1
 #     with:
 #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
 #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 #       
 #   - name: Build Env
 #     run: docker build ./OlympicGamesApp/OlympicGames.App --tag olympicgames
  #    
  #  - name: Docker tagging
 #     run: docker tag olympicgames ${{ secrets.DOCKER_HUB_USERNAME }}/p1:olympicgames
#      
#    - name: Deploy
#      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/p1:olympicgames
