name: Docker Image Publish

#env:
  
on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build Env
      run: docker build ./OlympicGamesApp/OlympicGames.App -t olympicgames:latest
      
    - name: Deploy
      uses: docker/build-push-action@v2
      with:
         context: .
         file: ./OlympicGamesApp/OlympicGames.App/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ymldocker
